### ISSUE TITLE
Running the building reconstruction with Docker- Modify config file to select all buildings

### ISSUE THREAD

**Issue by Mboga** [geoflow3d/geoflow-bundle#16]
Thank you for a nice tool. I have successfully run the docker implementation. But I have a question: How can you change the test-data/config.toml to allow for more than one building polygon to be processed. As of now, it is only possible to select and process one building polygon at a time. Thank you

**Comment by balazsdukai** [comment]
Hi, at the moment it is not possible to process multiple building polygons at once.
The idea is that you implement your own data processing pipeline that calls the building reconstruction as a subprocess and feeds it with the necessary polygon and point cloud data.
