### ISSUE TITLE
open file gpkg error

### ISSUE THREAD

**Issue by gustavo1976** [geoflow3d/geoflow-bundle#27]
I download the latest realease  Geoflow-2023.08.16-win64.exe an install it on windows system. When I installed it said that can not modified the path var so I added to the variable system  the path C:\Program Files\Geoflow\bin

After that I execute the comand
lod22-reconstruct --input_footprint=pruebas2.gpkg --input_pointcloud=prueba2.las
Both files exits and I can open them with qgis

And it gives me the next error:
Automatically loading flowchart C:\Program Files\Geoflow\share\geoflow\gfc-brecon\single\reconstruct.json
Detected environment variable GF_PLUGIN_FOLDER = C:\Program Files\Geoflow\lib\geoflow-plugins
key not found in node parameters: skip_LoD12
key not found in node parameters: skip_LoD13
key not found in node parameters: skip_LoD22
key not found in node parameters: only_horizontal
could not find one marked terminal
key not found in node parameters: only_horizontal
could not find one marked terminal
key not found in node parameters: feature_select
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
key not found in node parameters: epsg
key not found in node parameters: overwrite
ERROR: Error: Open failed on pruebas2.gpkg

I downladed the test data and gives me the same error

ERROR: Error: Open failed on wippolder.gpkg

**Comment by Mecak** [comment]
I got the same error message

ERROR: Error: Open failed on D:\Lidar\Layer.gpkg

**Comment by Ylannl** [comment]
This was fixed in version 2024.03.08
