### ISSUE TITLE
Documentation to get started

### ISSUE THREAD

**Issue by balazsdukai** [geoflow3d/geoflow-bundle#6]
- [x] What is geoflow and what is it not
- [x] The current status of geoflow
- [x] Tutorial on how to do the building reconstruction with test data in the CLI.
- [ ] Explain all the global parameters. Keep them in the TOML, just review them if they still up to date.
- [x] Describe and show what dir structure is created for the outputs.

**Comment by Ylannl** [comment]
Use the `flowcharts/gfc-brecon/single/reconstruct.json` flowchart. 
I added docstrings for the global parameters (check json or `geof run reconstruct.json --global`). I renamed and simplified things a bit. TOML could use same docstrings, just add some examples maybe for the DB connections string (default is gpkg).

**Comment by balazsdukai** [comment]
Btw what about the conflicting global parameters in `flowcharts/gfc-brecon/config.toml` and what is reported by `geof run lowcharts/gfc-brecon/single/reconstruct.json --globals`?
I assume the one in the flowchart is true for the flowchart itself.
But config.toml at the root of the repo also refers to the other two `reconstruct.json`-s, which have different globals already.
Should we remove config.toml altogether, or move it next to the flowchart?

**Comment by Ylannl** [comment]
My idea was to update the TOML with the new names. But maybe it is indeed a better idea to remove them (save the hassle of having to maintain them) and just explain in the documentation how it works (and example to connect to postgres DB).

Indeed the option from the command line with `-g` are the correct ones.
