### ISSUE TITLE
Enable LoD2 in github builds

### ISSUE THREAD

**Issue by balazsdukai** [geoflow3d/geoflow-bundle#7]
- [x] Enable lod2 in docker image, so that it takes the flowchart just like the windows exe. It is better to be consistent across the executables. Or do we need this?
- [x] Update the Installation section in the README with the new Lod2 exe-s.

**Comment by Ylannl** [comment]
I just enabled it for the windows builds, see https://github.com/geoflow3d/geoflow-bundle/commit/aa9e600e4c3388524c47308e52ddabb7188cfcb3 .
